### ISSUE TITLE
[Bug] QMK Toolbox can't be opened because apple cannpt check it for maliscous software.

### ISSUE THREAD

**Issue by janbridley** [qmk/qmk_firmware#12822] opened 2021-05-07 01:50 UTC
## Describe the Bug

QMK Toolbox does not run.

## System Information

MACOS Big Sur 11.3, M1 Chip

**Comment by fauxpark** [comment] 2021-05-07 09:46
Duplicate of https://github.com/qmk/qmk_toolbox/issues/227

**Closed by fauxpark** 2021-05-07 09:46 UTC
Labels: bug, help wanted
