### ISSUE TITLE
AUTO_SHIFT_ENABLE breaks ergodox infinity build

### ISSUE THREAD

**Issue by leshow** [qmk/qmk_firmware#2545] opened 2018-03-16 13:26 UTC
A keymap which compiles fine will fail to compile if `AUTO_SHIFT_ENABLE = yes` is added to `rules.mk`

```sh
Linking: .build/ergodox_infinity_leshowmap.elf                                                      [ERRORS]
 | 
 | /usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/lib/armv7e-m/libg.a(lib_a-sbrkr.o): In function `_sbrk_r':
 | /build/newlib-XAuz1P/newlib-2.4.0.20160527/build/arm-none-eabi/armv7e-m/newlib/libc/reent/../../../../../../newlib/libc/reent/sbrkr.c:58: undefined reference to `_sbrk'
 | collect2: error: ld returned 1 exit status
 | 
tmk_core/rules.mk:284: recipe for target '.build/ergodox_infinity_leshowmap.elf' failed
make[1]: *** [.build/ergodox_infinity_leshowmap.elf] Error 1
Make finished with errors
Makefile:528: recipe for target 'ergodox_infinity:leshowmap:dfu-util' failed
make: *** [ergodox_infinity:leshowmap:dfu-util] Error 1

```

**Comment by drashna** [comment] 2018-03-25 19:09
Duplicate of #2089.

Also fixed in #2608.  Update your repo and it will compile properly.

**Closed by drashna** 2018-03-25 19:09 UTC
