### ISSUE TITLE
tapdance does not work.

### ISSUE THREAD

**Issue by benji877** [qmk/qmk_firmware#756] opened 2016-09-14 00:17 UTC
By adding this line (#define KC_TD TD) I got it to compile, but if I double tap 1 (I want it to type !) it switches to layer one and stays there.

Keymap: http://pastebin.com/hGArVhhS

**Comment by algernon** [comment] 2016-09-14 05:14
Do you have `TAP_DANCE_ENABLE=yes` in your `Makefile`? Does single tapping work?

**Comment by benji877** [comment] 2016-09-14 05:15
Yes and yes.

**Comment by algernon** [comment] 2016-09-14 06:36
Hm. Can you try something for me? If you make a macro (and bind it to a key, of course) that does the following, does that input `!`, or does it switch to layer one?

```c
case M_TEST:
  if (record->event.pressed) {
    register_code16(KC_EXLM);
  } else {
    unregister_code16(KC_EXLM);
  }
  break
```

**Comment by algernon** [comment] 2016-09-14 06:37
Also, does double-tapping `2` work? Or does that switch to layer two?

**Comment by benji877** [comment] 2016-09-14 15:05
Double tapping 2 puts me into layer 2.

**Comment by algernon** [comment] 2016-09-14 15:14
Okay. Can you try the macro too? That will give me a general idea where to look for bugs.

Thanks!

**Comment by benji877** [comment] 2016-09-14 15:17
I will try it when I get home.

**Comment by algernon** [comment] 2016-09-23 05:36
@benji877 did you have a chance to try the macro? Unfortunately, I'm still unable to reproduce the problem :(

**Comment by benji877** [comment] 2016-09-23 05:37
Oops. I forgot. Yes, I will try to do it this weekend.

**Comment by skullydazed** [comment] 2017-06-27 04:25
I'm closing this to clean up our open issues, but if you still have questions @benji877 please reopen this or open a new issue.

**Closed by skullydazed** 2017-06-27 04:25 UTC
