### ISSUE TITLE
[Bug] Keyboard freezes after a few keystrokes

### ISSUE THREAD

**Issue by mvuksano** [qmk/qmk_firmware#12536] opened 2021-04-10 00:06 UTC
After a few keystrokes, keyboard does not produce any more key presses.

## Describe the Bug

I am using Massdrop OLKB keyboard with latest firmware. My intent was to create a log of key press events so I can further analyze it and create a heat map of my keyboard usage.

## System Information

 - Keyboard:  Massdrop OLKB
   - Revision (if applicable):  rev6
   - CPU: ARM STM32
 - Operating system: MacOS X and Linux (I have not tried Windows)
 - AVR GCC version: avr-gcc (Fedora 10.2.0-1.fc33) 10.2.0
 - ARM GCC version: arm-none-eabi-gcc (Fedora 10.2.0-2.fc33) 10.2.0
 - QMK Firmware version: 0.12.32
 - Any keyboard related software installed? None

## Additional Context

Following is the diff of the changes that cause the keyboard to stop responding. Without applying this diff the keyboard works as expected.

```diff
diff --git a/keyboards/planck/keymaps/marko/keymap.c b/keyboards/planck/keymaps/marko/keymap.c
index ab9899edb..7316e2697 100644
--- a/keyboards/planck/keymaps/marko/keymap.c
+++ b/keyboards/planck/keymaps/marko/keymap.c
@@ -17,6 +17,10 @@
 #include QMK_KEYBOARD_H
 #include "muse.h"
 
+#ifdef CONSOLE_ENABLE
+#include "print.h"
+#endif
+
 
 enum planck_layers {
   _QWERTY,
@@ -181,6 +185,11 @@ layer_state_t layer_state_set_user(layer_state_t state) {
 }
 
 bool process_record_user(uint16_t keycode, keyrecord_t *record) {
+  #ifdef CONSOLE_ENABLE
+    if (record->event.pressed) {
+      uprintf("0x04X,%u,%u,%u\n", keycode, record->event.key.row, record->event.key.col, get_highest_layer(layer_state));
+    }
+  #endif
   switch (keycode) {
     case QWERTY:
       if (record->event.pressed) {
diff --git a/keyboards/planck/keymaps/marko/rules.mk b/keyboards/planck/keymaps/marko/rules.mk
index 1b5789717..35cc9d5ef 100644
--- a/keyboards/planck/keymaps/marko/rules.mk
+++ b/keyboards/planck/keymaps/marko/rules.mk
@@ -1,3 +1,4 @@
 SRC += muse.c
 
 KEY_LOCK_ENABLE = yes
+CONSOLE_ENABLE = yes
```

**Comment by zvecr** [comment] 2021-04-10 14:46
Duplicate of #5631

**Closed by zvecr** 2021-04-10 14:46 UTC
Labels: bug, help wanted
