### ISSUE TITLE
[discussion] XD-002, a cool, new, but attiny85 2% keyboard

### ISSUE THREAD

**Issue by docteurzoidberg** [qmk/qmk_firmware#2734] opened 2018-04-12 14:27 UTC
I know what you are all thinking about right now while reading this:

"Oh no, not the tiny !" 
"we can't do anything on that uc !"
"so few space"

But I did a bet with a friend that qmk can run it !

Obvisouly I failed, i wans't able to compile either the timer.c and bootloader.c files with the V-USB stack at the current state of the QMK repository.

But TMK seems to compile actually for attin85, without a lot of functions of course.

So, is anyone able to guide me with re-enabling QMK on attiny85 so I may try to add this nice good looking 2 key keyboard to the repository ?

Many thanks for reading and advices !

**Comment by drashna** [comment] 2018-04-12 15:40
I think the problem here is that the th ATtiny85 is limited to 8KB of program space (assuming no bootloader).

The problem is that there is just too much in QMK that it won't fit.  Even testing a 6 key keyboard and disabling just about EVERYTHING, it was larger than 8KB. 

This is including tricks such as enabling linker optimization, which can greatly reduce the size.  The smallest I could get it was 8.2K.

**Comment by docteurzoidberg** [comment] 2018-04-15 17:59
thanks for your answer ! 

I will try to see what can be removed, but seems more logic to keep the old tmk for this keyboard actually. 

Maybe a custom replacement PCB design for running QMK would be better

**Comment by drashna** [comment] 2018-05-11 20:42
Progress?

**Comment by xtaran** [comment] 2018-08-24 18:43
@docteurzoidberg: Any pointer to TMK for the XD002? So far I just found TMK for single key keyboards with the ATtiny85.

**Comment by jackhumbert** [comment] 2020-03-17 17:23
I'm gonna close this for now - if you have any updates, feel free to share them here!

**Closed by jackhumbert** 2020-03-17 17:23 UTC
Labels: discussion, keyboard, optimization
