### ISSUE TITLE
RESET stops working after hardware reset until power cycled. 

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_firmware#1624] opened 2017-08-22 01:36 UTC
This is on the 0.5.107 build. on an ErgoDox EZ (Teensy 2.0 controller, I believe)

If you hit the hardware reset, the software RESET fails to work properly.

**Comment by jackhumbert** [comment] 2017-11-12 16:09
Duplicate of #164 :)

**Closed by jackhumbert** 2017-11-12 16:09 UTC
