### ISSUE TITLE
[Bug] redox_w broken by #15479 (Dec 2021 @fauxpark)

### ISSUE THREAD

**Issue by akavel** [qmk/qmk_firmware#17224] opened 2022-05-28 18:43 UTC
## Describe the Bug

I have a working Redox Wireless keyboard from falba.tech. I did the following actions today:

 1. Created a custom layout using the QMK Configurator, compiled and downloaded the `.hex` file, then flashed it using the QMK Toolbox. The flashing & verification completed successfully, but when I hit the keys, nothing happened on the connected computer.
 2. I downloaded the QMK-built `.hex` published by the original author of the keyboard to their repository at: https://github.com/mattdibi/redox-keyboard/blob/1ba788b0fee34c757ecb16d632d9c9d8d463de16/redox-w/firmware/qmk_redox_w_default.hex. I flashed it using the QMK Toolbox, and they keyboard started working fine again.
 3. I cloned the `qmk_firmware` repository. I tried building `.hex` files from various commits that modified the `keyboards/redox_w` directory. I observed that:
     - firmware built for redox_w from c12268807d8622a05dc445e6101a575eae16860d (#15479) by @fauxpark  and later commits does not work;
     - firmware built for redox_w from c0bb153151 (parent of the commit above) and earlier commits works fine.

## System Information

**Keyboard:** redox_w
**Revision (if applicable):** 
**Operating system:** Windows (QMK Toolbox for flashing), Linux (NixOS, for building .hex files)
**`qmk doctor` output:** 
```
(Paste output here)
```

**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [ ] Other:

## Additional Context

I could try debugging this further, but the commit that breaks this firmware appears to be quite big and intrusive and I'm not sure how to even start; also I have zero previous experience with firmware hacking & electronics.

**Comment by zvecr** [comment] 2022-05-28 18:49
Duplicate of #16553.

**Closed by zvecr** 2022-05-28 18:49 UTC
Labels: bug, duplicate, help wanted
