### ISSUE TITLE
steno is outputting incorrect keystrokes

### ISSUE THREAD

**Issue by xsrvmy** [qmk/qmk_firmware#4506] opened 2018-11-28 07:52 UTC
When I use TXBolt steno, the keystrokes that are outputted are incorrect. For example, the left T outputs a left T followed by a left W. I have already checked that this issue is not because of the keyboard itself since changing the layout does not change the incorrect output.

**Comment by drashna** [comment] 2018-12-09 21:43
I think this is a duplicate of this: https://github.com/qmk/qmk_firmware/issues/4578

(well, this was first, but that thread has more information, and may be helpful.

**Closed** 2019-02-24 03:32 UTC
Labels: bug, help wanted, question
