### ISSUE TITLE
can't install qmk with brew on macos catalina

### ISSUE THREAD

**Issue by nosleduc** [qmk/qmk_firmware#13994] opened 2021-08-13 19:39 UTC
## Describe the Bug

I tried to install qmk with brew on catalina and it failed, I got the following message

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "qmk"
Download failed: https://github.com/qmk/homebrew-qmk/releases/download/qmk-0.3.0/qmk-0.3.3.catalina.bottle.tar.gz

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by zvecr** [comment] 2021-08-13 22:13
Duplicate of qmk/homebrew-qmk#30

**Closed by zvecr** 2021-08-13 22:13 UTC
Labels: question, help wanted
