### ISSUE TITLE
QMK Configurator web site can't use keymap UI

### ISSUE THREAD

**Issue by tatsujin2006** [qmk/qmk_firmware#16500] opened 2022-03-03 03:09 UTC
QMK Configurator web site can't use keymap UI

![图片](https://user-images.githubusercontent.com/7369435/156488783-78e8a125-4a88-4660-af6a-5daea4de069c.png)

**Comment by fauxpark** [comment] 2022-03-03 03:25
Duplicate of https://github.com/qmk/qmk_configurator/issues/1093

**Closed by fauxpark** 2022-03-03 03:25 UTC
Labels: question, help wanted

**Comment by tatsujin2006** [comment] 2022-03-03 10:19
thanks
