### ISSUE TITLE
[Bug] Error compiling ws2812_setleds

### ISSUE THREAD

**Issue by carlosala** [qmk/qmk_firmware#17167] opened 2022-05-20 07:32 UTC
## Describe the Bug

There's a compilation error in the file platforms/avr/drivers/ws2812.c
## System Information

**Keyboard:** kprepublic/bm60hsrgb_poker
**Revision (if applicable):** 1
**Operating system:** Arch Linux
**`qmk doctor` output:** 
```
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.0.0
Ψ QMK home: /home/carlo/.qmk
Ψ Detected Linux.
Ψ Git branch: master
Ψ Repo version: 0.16.9
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 12.1.0
Ψ Found avr-gcc version 12.1.0
⚠ We do not recommend avr-gcc newer than 8. Downgrading to 8.x is recommended.
Ψ Found avrdude version 7.0
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found
```
**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [ ] Other:

## Additional Context

I paste here the output of the compilation:
```
Compiling: platforms/avr/drivers/ws2812.c                                                          platforms/avr/drivers/ws2812.c: In function 'ws2812_setleds':
platforms/avr/drivers/ws2812.c:43:45: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds]
   43 |     uint8_t masklo = ~(pinmask(RGB_DI_PIN)) & PORTx_ADDRESS(RGB_DI_PIN);
In function 'ws2812_sendarray_mask',
    inlined from 'ws2812_setleds' at platforms/avr/drivers/ws2812.c:46:5:
platforms/avr/drivers/ws2812.c:106:15: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds]
  106 |     sreg_prev = SREG;
      |               ^
platforms/avr/drivers/ws2812.c:171:10: error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds]
  171 |     SREG = sreg_prev;
      |          ^
cc1: all warnings being treated as errors
 [ERRORS]
```

**Comment by fauxpark** [comment] 2022-05-20 07:43
Duplicate of https://github.com/qmk/qmk_firmware/issues/17064

Downgrade your avr-gcc.

**Closed by fauxpark** 2022-05-20 07:43 UTC
Labels: bug, help wanted
