### ISSUE TITLE
Support getting the serial number from Input Club keyboards

### ISSUE THREAD

**Issue by belak** [qmk/qmk_firmware#2142] opened 2017-12-12 01:38 UTC
There's some background information in https://github.com/qmk/qmk_firmware/pull/1963#issuecomment-342670875

Essentially, we can pull the serial information from some magical registers and should be able to export it in the USB information

**Comment by jackhumbert** [comment] 2020-03-17 17:17
I think this is a duplicate of #2670

**Closed by jackhumbert** 2020-03-17 17:17 UTC
Labels: duplicate, enhancement, help wanted, to do
