### ISSUE TITLE
Added issues with new MCU models

### ISSUE THREAD

**Issue by joylee210** [qmk/qmk_firmware#13766] opened 2021-07-29 02:42 UTC
I added a non-STM32 Cortex-M3 core MCU, but the keboards folder cannot contain McUconf. h file.
![Snipaste_2021-07-29_10-41-38](https://user-images.githubusercontent.com/71184547/127423245-aa16e0e4-ec52-4dfa-a381-baba9c2d3bf5.png)

**Comment by tzarc** [comment] 2021-07-29 02:52
Please provide more information. You can add mcuconf.h.

**Comment by joylee210** [comment] 2021-07-29 02:57
The Mcuconf. h file ， included in keboards cannot be compiled at compile time，The McUconf. h file in the flatForms folder can be compiled

**Comment by joylee210** [comment] 2021-07-29 02:59
![Uploading Snipaste_2021-07-29_10-59-02.png…]()

**Comment by joylee210** [comment] 2021-07-29 03:01
I don't know if I need to change the makefile when I add the MCU

**Comment by joylee210** [comment] 2021-07-29 03:01
![Snipaste_2021-07-29_10-59-02](https://user-images.githubusercontent.com/71184547/127424905-572ba454-edc7-4fa4-b638-c9776dba301f.png)

**Comment by joylee210** [comment] 2021-07-29 03:02
With the exception of the McUconf. h file, QMK compacts properly and is usable

**Comment by joylee210** [comment] 2021-07-29 03:05
With the exception of the McUconf. h file, QMK can be compiled and the keyboard can work properly

**Comment by joylee210** [comment] 2021-07-29 07:01
![image](https://user-images.githubusercontent.com/71184547/127446642-c553ee7d-6ee6-475c-97c5-8bc7baa59a20.png)

**Comment by joylee210** [comment] 2021-07-29 07:04
Is it need to add MCU support anywhere else in your Python script file

**Comment by fauxpark** [comment] 2021-07-29 07:17
To add support for a new MCU (which is supported by ChibiOS), you will at least need to modify the following files/folders:

* `data/schemas/keyboard.jsonschema`
* `docs/compatible_microcontrollers.md` (add link to product page)
* `lib/python/qmk/constants.py`
* `platforms/chibios/` (add board files and default configs)
* `quantum/mcu_selection.mk`

There may be more modifications necessary in other files to support certain hardware features. Do note that if this MCU is *not* currently supported by ChibiOS we are unlikely to merge support for it here unless you first submit your contributions to ChibiOS itself.

**Comment by joylee210** [comment] 2021-07-29 07:25
@fauxpark  I've added all of that，Drivers have also been added to chiBIOS，The Mcuconf. h file in The Keyboards folder still needs to be included, but I haven't found the reason. I see that the path is included in the build Keyboard. Mk file, but it's still not compiled into it 
![Uploading Snipaste_2021-07-29_15-24-24.png…]()

**Comment by joylee210** [comment] 2021-07-29 07:25
![Snipaste_2021-07-29_15-24-24](https://user-images.githubusercontent.com/71184547/127449757-acb20490-4068-424c-9da7-16451e553337.png)

**Comment by joylee210** [comment] 2021-07-29 07:26
I don't understand why you need to include the Mcuconf.h file as well

**Comment by fauxpark** [comment] 2021-07-29 07:31
> I don't understand why you need to include the Mcuconf.h file as well

You don't. What is the error you're getting? You've just said "it cannot be compiled". That's not much to go on.

**Comment by joylee210** [comment] 2021-07-29 07:38
no error , I want to change the MCU configuration, but only mcuconf. h in Platforms folder is valid, and mcuconf. h in Mandolin. folder is invalid

**Comment by joylee210** [comment] 2021-07-29 07:40
Do you understand chinese? My English is so bad.
I want to be able to communicate in Chinese.

**Comment by joylee210** [comment] 2021-07-29 07:40
@fauxpark

**Comment by fauxpark** [comment] 2021-07-29 08:17
From what I can tell, your mcuconf.h is using the simplified format generated by `qmk chibios-confmigrate`. This contains the line `#include_next <mcuconf.h>`, which means there must exist a "full" mcuconf.h in `platforms/chibios` under the directory for this WB32 board, for example:
![image](https://user-images.githubusercontent.com/4781841/127456677-a93fe28e-38fc-4a6e-90fb-89fcf68c655a.png)

Your WB32F103 block in `mcu_selection.mk` must reference the name of this folder - in this case for `STM32F072`, there is the line `BOARD ?= GENERIC_STM32_F072XB`.

**Comment by fauxpark** [comment] 2021-07-29 08:21
Another thing I have noticed is that I don't see WB32 anywhere in:

https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x/os/hal/ports
https://github.com/ChibiOS/ChibiOS/tree/master/os/hal/ports

So I am assuming you have manually modified the `chibios` and `chibios-contrib` submodules inside `qmk_firmware/lib` to add support.

**Comment by joylee210** [comment] 2021-07-29 09:05
@fauxpark  My chiBIOS code has not been submitted, boards have been added in platforms/ CHIBIOS

**Comment by joylee210** [comment] 2021-07-29 09:09
![Snipaste_2021-07-29_17-07-33](https://user-images.githubusercontent.com/71184547/127464891-7a7d9e7c-e276-449a-842f-7879c92450cb.png)
![Snipaste_2021-07-29_17-08-58](https://user-images.githubusercontent.com/71184547/127464898-8bbd2428-e4cc-4371-8a2b-5bb0f6401e10.png)

**Comment by joylee210** [comment] 2021-07-29 09:10
![Snipaste_2021-07-29_17-10-38](https://user-images.githubusercontent.com/71184547/127465154-dcaa9ed8-69c9-4425-a4a9-86bab062ef44.png)

**Comment by fauxpark** [comment] 2021-07-29 09:38
Okay, so you seem to know what you're doing then. I'm still not sure what you mean by this though:
> The Mcuconf. h file ， included in keboards cannot be compiled at compile time，The McUconf. h file in the flatForms folder can be compiled

Is the problem that the keyboard-level `mcuconf.h` is not overriding the platform-level one? ie. the `WB32_I2C_USE_I2C1 TRUE` line only works if you set it in `platforms/chibios/WB32_EVAL/configs/mcuconf.h`?

**Comment by joylee210** [comment] 2021-07-29 09:39
ye ， I don't know how to solve it

**Comment by joylee210** [comment] 2021-07-29 09:39
@fauxpark

**Comment by joylee210** [comment] 2021-07-30 01:18
Do you know what caused it @fauxpark

**Comment by tzarc** [comment] 2021-08-02 18:16
Delete the keyboard's `mcuconf.h` file.

**Comment by joylee210** [comment] 2021-08-03 01:37
@tzarc  Is there no other solution ?

**Comment by tzarc** [comment] 2021-08-03 01:43
Can you explain what you're trying to do, and why? There's no reason for the `mcuconf.h` in the keyboard if you've already got one in `platforms/chibios/XXXXXXXXXX/configs`.

**Comment by joylee210** [comment] 2021-08-03 01:45
@tzarc  I just want to be able to modify the configuration directly on the Keyboard's, so it's a little more convenient, and I've seen other Keyboards do that  .

**Comment by tzarc** [comment] 2021-08-03 01:50
I don't understand why you made all the other modifications, then. The makefiles and platforms are already set up to allow for that file to be included - no core makefile modifications are required, and the paths should be automatic.

I can't tell what the problem is because you've never pasted the error.

I'd suggest reverting any modifications done to any of the core makefiles -- unless absolutely necessary they won't get merged.

**Comment by joylee210** [comment] 2021-08-03 01:56
@tzarc  For the makefile, I only added the modifications for the MCU, nothing else was changed, and I don't know why mcuconf. h is not included. I also see that the makefile already includes the path.
The problem now is that I want to find out why mcuconf.h was not compiled when the makefile already included the path.

**Comment by tzarc** [comment] 2021-08-03 02:01
Can you do a build, and attach: `.build/obj_wb_keyboards_gsky_1_default/cflags.txt` please?

**Comment by joylee210** [comment] 2021-08-03 02:04
[cflags.txt](https://github.com/qmk/qmk_firmware/files/6920517/cflags.txt)
@tzarc

**Comment by tzarc** [comment] 2021-08-03 02:07
Given the parameters, it's already set up to include `mcuconf.h`.
You're going to have to paste the error -- there's nothing wrong with the build arguments.

**Comment by joylee210** [comment] 2021-08-03 02:10
![Snipaste_2021-08-03_10-09-53](https://user-images.githubusercontent.com/71184547/127946558-ab43179c-b218-41c6-a842-2edf155f222b.png)

@tzarc

**Comment by joylee210** [comment] 2021-08-03 02:11
path: keyboards\wb_keyboards\gsky_1\rev1\mcuconf.h

**Comment by tzarc** [comment] 2021-08-03 02:12
And what is being checked on:
`lib/chibios-contrib/os/hal/ports/WB32/LLD/I2Cv1/hal_i2c_lld.h`, line 236?

**Comment by joylee210** [comment] 2021-08-03 02:13
![Snipaste_2021-08-03_10-13-01](https://user-images.githubusercontent.com/71184547/127946809-290a106d-d1ee-420d-a016-a6f1d9a13fb6.png)
This is already enabled in mcuconf.h
@tzarc

**Comment by joylee210** [comment] 2021-08-03 02:15
This error occurs because the keyboards\wb_keyboards\gsky_1\rev1\mcuconf.h file has not been compiled into it
@tzarc

**Comment by tzarc** [comment] 2021-08-03 02:16
Please upload:
`keyboards/wb_keyboards/gsky_1/rev1/mcuconf.h` 
`platforms/chibios/WB32F103_EVAL/configs/mcuconf.h`
`lib/chibios-contrib/os/hal/ports/WB32/LLD/I2Cv1/hal_i2c_lld.h`

**Comment by joylee210** [comment] 2021-08-03 02:24
[hal_i2c_lld.txt](https://github.com/qmk/qmk_firmware/files/6920616/hal_i2c_lld.txt)
[platform_mcuconf.h.txt](https://github.com/qmk/qmk_firmware/files/6920617/platform_mcuconf.h.txt)
[keyboard_mcuconf.h.txt](https://github.com/qmk/qmk_firmware/files/6920618/keyboard_mcuconf.h.txt)
@tzarc

**Comment by tzarc** [comment] 2021-08-03 02:36
I can't tell from these files without being able to build myself.
I'd recommend pushing your branches of both qmk_firmware and ChibiOS-Contrib to personal forks, so we can investigate.

**Comment by joylee210** [comment] 2021-08-03 02:38
ok

**Comment by joylee210** [comment] 2021-08-03 09:57
Link to my warehouse : [https://github.com/joylee210/qmk_firmware.git  branch JoyLee](url) , branch JoyLee.
@tzarc

**Comment by joylee210** [comment] 2021-08-03 09:58
Link to my warehouse :   [https://github.com/joylee210/qmk_firmware.git](url)  , branch JoyLee , branch JoyLee.
@tzarc

**Comment by joylee210** [comment] 2021-08-03 09:59
Link to my warehouse : https://github.com/joylee210/qmk_firmware.git , branch JoyLee , branch JoyLee.
@tzarc

**Comment by joylee210** [comment] 2021-08-04 02:50
Did you figure out the structure ？ @tzarc

**Closed** 2021-09-13 04:57 UTC
Labels: question, help wanted
