### ISSUE TITLE
[Bug] The problem about pin PA9 on stm32f4

### ISSUE THREAD

**Issue by zhaqian12** [qmk/qmk_firmware#15975] opened 2022-01-21 07:42 UTC
## Describe the Bug
If I want to use PA9 as GPIO,it will have some problems.After browsing the code,I found VBUSBSEN bit enabled for the relevant register GCCFG in usb configuration in chibios and I think VBUS Sensing B device should also be disabled to make PA9 normal.

## System Information

 - Keyboard:  blackpill_stm32_f401/f411
 - Operating system:win10
 - AVR GCC version: 5.4.0
 - ARM GCC version: 9.2.1
 - QMK Firmware version:0.15.12
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by zvecr** [comment] 2022-01-21 14:21
Duplicate of #7855

**Closed by zvecr** 2022-01-21 14:21 UTC
Labels: bug, duplicate, help wanted
