### ISSUE TITLE
Operation not permitted - /usr/local/opt/avr-gcc/avr

### ISSUE THREAD

**Issue by Miodec** [qmk/qmk_firmware#1535] opened 2017-08-02 17:24 UTC
Hi, i cant brew install avr-libc

![screen shot 2017-08-02 at 18 23 02](https://user-images.githubusercontent.com/13181393/28886084-17ceb288-77b0-11e7-8348-94a5ccc59c5f.png)

**Comment by Maartenwut** [comment] 2017-08-02 18:57
Try running it as root?

**Comment by Miodec** [comment] 2017-08-02 20:23
Brew cant be ran as root

![screen shot 2017-08-02 at 21 23 14](https://user-images.githubusercontent.com/13181393/28893313-dbfe5b96-77c8-11e7-97c6-20d9db867106.png)

**Comment by Maartenwut** [comment] 2017-08-02 20:28
What about `brew doctor`?

**Comment by Miodec** [comment] 2017-08-02 20:32
Tried it already
![screen shot 2017-08-02 at 21 32 08](https://user-images.githubusercontent.com/13181393/28893622-146bc170-77ca-11e7-8e08-fa861b56cac4.png)

**Comment by skullydazed** [comment] 2017-08-02 20:39
Does anyone besides you use that machine? It's possible you have conflicting permissions. You can use this to force everything over to your user:

`sudo chown -R $USER /usr/local`

Be warned that if you have mysql (or certain other server packages installed) that may break them.

**Comment by Miodec** [comment] 2017-08-02 20:47
Didnt work 
![screen shot 2017-08-02 at 21 47 27](https://user-images.githubusercontent.com/13181393/28894284-3aa734bc-77cc-11e7-9248-1fd8b4ac9815.png)

**Comment by nooges** [comment] 2017-08-03 05:25
After talking to @Miodec, turns out the issue is due to Homebrew now turning on sandboxing for all non-homebrew taps, which prevents the final copy operation from succeeding.

I've added a comment to this issue with the homebrew-avr tap: https://github.com/osx-cross/homebrew-avr/issues/19

**Comment by nooges** [comment] 2017-08-04 11:54
This should be resolved now that https://github.com/osx-cross/homebrew-avr/pull/54 has been merged, which closes https://github.com/osx-cross/homebrew-avr/issues/19.

**Closed** 2017-10-22 08:20 UTC
