### ISSUE TITLE
Use of tap_code_delay being described as 'implicit declaration'

### ISSUE THREAD

**Issue by CrisHale** [qmk/qmk_firmware#14804] opened 2021-10-12 18:14 UTC
I've used the tap_code_delay function to try to resolve an issue where setting up the KC_MNXT keycode with a leader key is resulting in sticky behaviour - which I assume is down to the key not unregistering properly - and I'm being told by the compiler (or at least the command line of this MSYS software) that the function is being implicitly declared.

## System Information

 - Keyboard:  Plaid
   - Revision (if applicable):  
 - Operating system: Windows 10
 - AVR GCC version: 8.3.0

 - ARM GCC version: 8.3.1 20190703

 - QMK Firmware version: fatal: not a git repository (or any of the parent directories): .git (Yes, I know this isn't actually a version, but I don't know what to do about it)

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by zvecr** [comment] 2023-11-14 02:45
With no git version to reference, and being unable to reproduce, closing.

**Closed by zvecr** 2023-11-14 02:45 UTC
Labels: bug, help wanted
