### ISSUE TITLE
[Feature Request] Only send the last pressed key

### ISSUE THREAD

**Issue by darix** [qmk/qmk_firmware#24166] opened 2024-07-21 15:32 UTC
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

To basically implement what can be seen here

https://www.youtube.com/watch?v=Feny5bs2JCg

**Comment by miathetrain** [comment] 2024-07-21 19:16
Duplicate of https://github.com/qmk/qmk_firmware/pull/24000

**Closed** 2024-07-21 19:23 UTC
Labels: enhancement, help wanted

**Comment by Geczy** [comment] 2024-08-19 02:19
whats up with that pr? why's it taking so long @darix
