### ISSUE TITLE
[Feature Request] Settings changed by the user for the drop CTRL should persist

### ISSUE THREAD

**Issue by ShrinivasKR** [qmk/qmk_firmware#12804] opened 2021-05-05 00:10 UTC
Can the changes outlined in the below link be implemented for the Drop Ctrl keyboard keymaps so user settings persist?
https://www.travisgeis.com/2020/10/05/adding-persistent-settings-to-drop-ctrl/

**Comment by tzarc** [comment] 2021-05-05 03:03
dupe of #4625, #6068.

**Closed by tzarc** 2021-05-05 03:03 UTC
